version: '3.9'

services:
  node1:
    image: alpine:latest
    container_name: node1
    command: sh -c "while true; do sleep 3600; done"
    pull_policy: always

  log-viewer:
    build:
      context: ./log-viewer/
      dockerfile: Dockerfile
    container_name: log-viewer
    ports:
      - "5000:5000"
    pull_policy: always
    volumes:
      - shared_logs:/var/log/styx

  firewall:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firewall
    user: root
    privileged: true
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    volumes:
      - shared_logs:/var/log/styx

volumes:
  shared_logs:
    driver: local
