
services:
  node1:
    image: alpine:latest
    container_name: node1
    command: sh -c "while true; do sleep 3600; done"
    pull_policy: always
  firewall:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firewall
    user: root
    privileged: true
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
